<!--- CTR Custom Header Possibilities --->
<script src="https://www.nmchiptuning.nl/wp-content/plugins/elementor/assets/lib/jquery-numerator/jquery-numerator.js?ver=0.2.1" id="jquery-numerator-js"></script>
<script src="https://www.nmchiptuning.nl/wp-content/plugins/elementor-pro/assets/js/webpack-pro.runtime.js?ver=3.22.1" id="elementor-pro-webpack-runtime-js"></script>
<script src="https://www.nmchiptuning.nl/wp-content/plugins/elementor/assets/js/webpack.runtime.js?ver=3.22.3" id="elementor-webpack-runtime-js"></script>
<script src="https://www.nmchiptuning.nl/wp-content/plugins/elementor/assets/js/frontend-modules.js?ver=3.22.3" id="elementor-frontend-modules-js"></script>
<script id="elementor-pro-frontend-js-before">
var ElementorProFrontendConfig = {"ajaxurl":"https:\/\/www.nmchiptuning.nl\/wp-admin\/admin-ajax.php","nonce":"b6480554a8","urls":{"assets":"https:\/\/www.nmchiptuning.nl\/wp-content\/plugins\/elementor-pro\/assets\/","rest":"https:\/\/www.nmchiptuning.nl\/wp-json\/"},"shareButtonsNetworks":{"facebook":{"title":"Facebook","has_counter":true},"twitter":{"title":"Twitter"},"linkedin":{"title":"LinkedIn","has_counter":true},"pinterest":{"title":"Pinterest","has_counter":true},"reddit":{"title":"Reddit","has_counter":true},"vk":{"title":"VK","has_counter":true},"odnoklassniki":{"title":"OK","has_counter":true},"tumblr":{"title":"Tumblr"},"digg":{"title":"Digg"},"skype":{"title":"Skype"},"stumbleupon":{"title":"StumbleUpon","has_counter":true},"mix":{"title":"Mix"},"telegram":{"title":"Telegram"},"pocket":{"title":"Pocket","has_counter":true},"xing":{"title":"XING","has_counter":true},"whatsapp":{"title":"WhatsApp"},"email":{"title":"Email"},"print":{"title":"Print"},"x-twitter":{"title":"X"},"threads":{"title":"Threads"}},"facebook_sdk":{"lang":"nl_NL","app_id":""},"lottie":{"defaultAnimationUrl":"https:\/\/www.nmchiptuning.nl\/wp-content\/plugins\/elementor-pro\/modules\/lottie\/assets\/animations\/default.json"}};
</script>
<script src="https://www.nmchiptuning.nl/wp-content/plugins/elementor-pro/assets/js/frontend.js?ver=3.22.1" id="elementor-pro-frontend-js"></script>
<script id="elementor-frontend-js-before">
var elementorFrontendConfig = {"environmentMode":{"edit":false,"wpPreview":false,"isScriptDebug":true},"i18n":{"shareOnFacebook":"Deel via Facebook","shareOnTwitter":"Deel via Twitter","pinIt":"Pin dit","download":"Downloaden","downloadImage":"Download afbeelding","fullscreen":"Volledig scherm","zoom":"Zoom","share":"Delen","playVideo":"Video afspelen","previous":"Vorige","next":"Volgende","close":"Sluiten","a11yCarouselWrapperAriaLabel":"Carrousel | Horizontaal scrollen: pijl links & rechts","a11yCarouselPrevSlideMessage":"Vorige slide","a11yCarouselNextSlideMessage":"Volgende slide","a11yCarouselFirstSlideMessage":"Ga naar de eerste slide","a11yCarouselLastSlideMessage":"Ga naar de laatste slide","a11yCarouselPaginationBulletMessage":"Ga naar slide"},"is_rtl":false,"breakpoints":{"xs":0,"sm":480,"md":768,"lg":1025,"xl":1440,"xxl":1600},"responsive":{"breakpoints":{"mobile":{"label":"Mobiel portret","value":767,"default_value":767,"direction":"max","is_enabled":true},"mobile_extra":{"label":"Mobiel landschap","value":880,"default_value":880,"direction":"max","is_enabled":false},"tablet":{"label":"Tablet portret","value":1024,"default_value":1024,"direction":"max","is_enabled":true},"tablet_extra":{"label":"Tablet landschap","value":1200,"default_value":1200,"direction":"max","is_enabled":false},"laptop":{"label":"Laptop","value":1366,"default_value":1366,"direction":"max","is_enabled":false},"widescreen":{"label":"Breedbeeld","value":2400,"default_value":2400,"direction":"min","is_enabled":false}}},"version":"3.22.3","is_static":false,"experimentalFeatures":{"e_optimized_assets_loading":true,"e_optimized_css_loading":true,"e_font_icon_svg":true,"additional_custom_breakpoints":true,"e_swiper_latest":true,"e_onboarding":true,"theme_builder_v2":true,"hello-theme-header-footer":true,"home_screen":true,"editor_v2":true,"landing-pages":true,"e_lazyload":true,"display-conditions":true,"form-submissions":true,"taxonomy-filter":true},"urls":{"assets":"https:\/\/www.nmchiptuning.nl\/wp-content\/plugins\/elementor\/assets\/"},"swiperClass":"swiper","settings":{"page":[],"editorPreferences":[]},"kit":{"active_breakpoints":["viewport_mobile","viewport_tablet"],"global_image_lightbox":"yes","lightbox_enable_counter":"yes","lightbox_enable_fullscreen":"yes","lightbox_enable_zoom":"yes","lightbox_enable_share":"yes","lightbox_title_src":"title","lightbox_description_src":"description","hello_header_logo_type":"title","hello_header_menu_layout":"horizontal","hello_footer_logo_type":"logo"},"post":{"id":2,"title":"nmchiptuning.nl","excerpt":"","featuredImage":false},"user":{"roles":["administrator"]}};
</script>

<script src="https://www.nmchiptuning.nl/wp-content/plugins/elementor/assets/lib/waypoints/waypoints.js?ver=4.0.2" id="elementor-waypoints-js"></script>
<script src="https://www.nmchiptuning.nl/wp-content/plugins/elementor/assets/js/frontend.js?ver=3.22.3" id="elementor-frontend-js"></script>
<script src="https://www.nmchiptuning.nl/wp-content/plugins/elementor-pro/assets/js/elements-handlers.js?ver=3.22.1" id="pro-elements-handlers-js"></script>
